name: Test on MacOS ARM and Push

on:
  workflow_dispatch:

# This workflow is triggered manually from the Actions tab.
# running on MacOS ARM only

jobs:
  publish:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jerrinot/questdb
      - name: Install tooling
        run: |
          brew install make cmake gcc
      - name: Go to the build directory
        run: |
          cd core
          cmake -B build/release -DCMAKE_BUILD_TYPE=Release
          cmake --build build/release --config Release
          cd ..
      - name: Commit the file
        run: |
          git config --global user.name 'GitHub Actions - ARM build'
          git config --global user.email 'jaromir@questdb.io'
          git add core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
          git commit -m "Rebuild MacOS ARM"

