name: Test on FreeBSD

on:
  workflow_dispatch:

# This workflow is triggered manually from the Actions tab.
# running on MacOS ARM only

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jerrinot/questdb
      - name: Build in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl cmake gcc git nasm openjdk17
          run: |
            export JAVA_HOME=/usr/local/openjdk17
            cd core
            cmake -B build/release -DCMAKE_BUILD_TYPE=Release
            cmake --build build/release --config Release
      - name: log git status
        run: |
          git status
      - name: Save Binary to Cache
        uses: actions/cache/save@v3
        with:
          path: |
            core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
          # cache key format: nativelibs-freebsd-<commit hash>
          key: nativelibs-freebsd-${{ github.sha }}
  build-macos-arm:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jerrinot/questdb
      - name: Install tooling
        run: |
          brew install make cmake gcc
      - name: Go to the build directory
        run: |
          cd core
          cmake -B build/release -DCMAKE_BUILD_TYPE=Release
          cmake --build build/release --config Release
          cd ..
      - name: Save Binary to Cache
        uses: actions/cache/save@v3
        with:
          path: |
            core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
          key: nativelibs-macosarm-${{ github.sha }}
  collect-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jerrinot/questdb
      - name: Restore FreeBSD binary from Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            core/src/main/resources/io/questdb/bin/freebsd/libquestdb.so
          key: nativelibs-freebsd-${{ github.sha }}
      - name: Restore MacOS ARM binary from Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
          key: nativelibs-macosarm-${{ github.sha }}
      - name: Check git status
        run: |
          git status