name: Test on MacOS ARM and Push

on:
  workflow_dispatch:

# This workflow is triggered manually from the Actions tab.
# running on MacOS ARM only

jobs:
  publish:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Run integration tests
        run: mvn -B test
      - name: Create a file
        run: |
          touch $HOME/created-file.txt
          echo "Hello World" > created-file.txt
      - name: Commit the file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'jaromir.hamala@gmail.com'
          git add created-file.txt
          git commit -m "Add created-file.txt"
      - name: Push the file
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

