name: Test on FreeBSD

on:
  workflow_dispatch:

# This workflow is triggered manually from the Actions tab.
# running on MacOS ARM only

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jerrinot/questdb

      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl cmake gcc git
          run: |
            cd core
            cmake -B build/release -DCMAKE_BUILD_TYPE=Release
            cmake --build build/release --config Release
      - name: logs stuff
        run: |
          git status
#      - name: Go to the build directory
#        run: |
#          cd core
#          cmake -B build/release -DCMAKE_BUILD_TYPE=Release
#          cmake --build build/release --config Release
#          cd ..
#      - name: Commit the file
#        run: |
#          git config --global user.name 'GitHub Actions - ARM build'
#          git config --global user.email 'jaromir@questdb.io'
#          git add core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
#          git commit -m "Rebuild MacOS ARM"
#
