name: Build and Publish Native Libraries

on:
  workflow_dispatch:
# This workflow is triggered manually from the Actions tab.

jobs:
  collect-commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: add a file with a random name
        run: |
            echo "test" > $(date +%Y_%m_%d_%H_%M_%S).txt
      - name: Commit the files
        run: |
          git config --global user.name 'GitHub Actions - Rebuild Native Libraries'
          git config --global user.email 'jaromir.hamala@questdb.io'
          git commit -am "random file added"
      - name: Push the changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}


